# Generated by Django 3.1.7 on 2021-03-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_todo_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.AddField(
            model_name='category',
            name='icon_code',
            field=models.PositiveIntegerField(default=62439),
            preserve_default=False,
        ),
    ]
